### ISSUE TITLE
add-extension generator leads to JS error after defining options

### ISSUE THREAD

**Issue by lehnerchristian** [phovea/generator-phovea#109]
* Release number or git hash: latest
* OS: Linux

### Steps to reproduce

1. `yo phovea:add-extension`
2. fill out the prompts
3. the last prompt (adding the extension description) leads to an error after adding `key=value` pairs (each in a new line) and saving

### Observed behavior
```
TypeError: Cannot read property 'trim' of undefined
    at text.split.forEach (/home/christian/.nvm/versions/node/v6.9.4/lib/node_modules/generator-phovea/generators/add-extension/index.js:12:18)
    at Array.forEach (native)
    at toJSONFromText (/home/christian/.nvm/versions/node/v6.9.4/lib/node_modules/generator-phovea/generators/add-extension/index.js:10:20)
    at prompt.then (/home/christian/.nvm/versions/node/v6.9.4/lib/node_modules/generator-phovea/generators/add-extension/index.js:72:17)

```

### Expected behavior
* should create an extension

**Comment by sgratzl** [comment]
can't reproduce on my windows machine.
