### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by thinkh** [phovea/generator-phovea#320]
With PR #165 we introduced some release templates that provide checklists for preparing a release. There is also a `prepare-release` generator that might perform similar steps. However, it might be broken due to changes in our infrastructure (e.g., remove Travis #274).

- [ ] Create dummy repository in personal user
- [ ] `yo phovea:init-lib-slib` (without phovea dependencies; develop branch)
- [ ] Test `yo phovea:prepare-release` --> document errors?

- [ ] Check steps in https://github.com/phovea/generator-phovea/blob/65c254ec56d2d04b2a29fd4d56133019460e1352/generators/_init-hybrid/templates/plain/.github/PULL_REQUEST_TEMPLATE/release.md
- [ ] Perform release following the template
- [ ] Use `npm publish --dry-run` and check something similar for twine

**Comment by oltionchampari** [comment]
- We discussed that to decide which packages are going to be published to `npm` , to `Pip `or not published at all , an entry published is going to be added to the `.yo-rc.json` file in every repository.
- The generator will read this config and act accordingly.
- In order to use the github api an access token needs to be created.Thus a `datavisyn bot` `access_token` and a `caleydo_bot  access-token`  has been created and can be found in `keeweb`.
To use the release generator these `access tokens` need to be provided the first time and then the generator will remember them.

**Comment by anita-steiner** [comment]
according to our last discussion, the `yo phovea:prepare-release` should to the following:

- Check next version for current repo depending on the labels of the merged PRs in the develop branch since the last release
- Prompt user to accept or define a different version number 
- Create release branch: release-<NEW-VERSION-NUMBER>
- Prompt user if he wants to update the dependencies of knownPlugins (plugins known by the generator)
- If yes: Update dependencies based on knownPlugins 
- Gather release notes from merged PRs (since the last release) 
- Show list to user and allow modification of the list (e.g., to fix typos)
- Update CHANGELOG.md with a new section at the top
- Push release branch to GitHub
- Create release PR 
- Add labels to PR
- Assign reviewer and assignee for PR

The user has to review the PR on GitHub and merge the release branch into the master branch → this triggers the following finalize release step via CircleCI:

**Comment by oltionchampari** [comment]
> according to our last discussion, the `yo phovea:prepare-release` should to the following:
> 
> * Check next version for current repo depending on the labels of the merged PRs in the develop branch since the last release
> * Prompt user to accept or define a different version number
> * Create release branch: release-
> * Prompt user if he wants to update the dependencies of knownPlugins (plugins known by the generator)
> * If yes: Update dependencies based on knownPlugins
> * Gather release notes from merged PRs (since the last release)
> * Show list to user and allow modification of the list (e.g., to fix typos)
> * Update CHANGELOG.md with a new section at the top
> * Push release branch to GitHub
> * Create release PR
> * Add labels to PR
> * Assign reviewer and assignee for PR
> 
> The user has to review the PR on GitHub and merge the release branch into the master branch → this triggers the following finalize release step via CircleCI:

What about the release templates?

**Comment by anita-steiner** [comment]
so what we have to change / add in the generator is the following:
* new method: prepare-release (as described above)
* new method: tag-release (as described above)
* new method: prepare-develop (as described above)
* change methods init-* (like init-lib, ) to add a correct circleCI config for all plugins (except products)
* change release templates:  release.md

**Comment by oltionchampari** [comment]
To test the first part of the realease ( till the PR ):
* please add an entry at https://github.com/phovea/generator-phovea/blob/c1554f779f12a413c8d562a39855ffe93aa2eea3/knownRepositories.json#L7
with your name and your repository name.
* run `yo phovea:prepare-release <repo name> --verbose`
* Make sure you have something to release ( some commits on develop ).

**Comment by oltionchampari** [comment]
A short demo with a hybrid plugin:
![demo](https://user-images.githubusercontent.com/51322092/76741797-6ebb7b00-6770-11ea-956f-30ac9dfdfa4f.gif)

**Comment by oltionchampari** [comment]
In my current implementation, i have hardcoded the fact that tdp_core and tdp_ui are unpublished so that version string can be a of the format:
` "tdp_core": "github:datavisyn/tdp_core#semver:^8.0.0" `
instead of :
` "tdp_core": "^8.0.0" `.
The same applies for unpublished requirements.

**Comment by thinkh** [comment]
The release consist of two main phases

1. Prepare release
2. Finalize release


# Prepare release

The release process is triggered on demand from a user. All steps that require user input are indicated with the 👩‍💻 emoji.

1. 👩‍💻 User is in the repo that should be released
2. 👩‍💻 From the develop branch the user runs `yo phovea:prepare-release`

The command will execute the following steps

## 1. Check for new versions of dependencies from _package.json_

**General information**

* This step is only necessary for web and hybrid plugins.
* Output of this step is that all develop dependencies are replaced with version numbers.

**Steps**

1. Gather github develop dependencies from _package.json_ (e.g., `github:phovea/phovea_core#develop`)
   * Check if that github link contains `phovea`, `caleydo`, `datavisyn`
   * Tip: Transform link to lower-case first to avoid different lower and upper case
2. For each dependency found:
   * Check on npmjs.com if package available
   * If available: get last version number and replace github develop dependency with npm version number (e.g., `^4.0.0`)
   * If not available: Check github repository for last release and replace github develop dependency with github semver dependency (e.g., `github:phovea/phovea_core#semver:^4.0.0`)
      * 👩‍💻 Request bot token from user (if necessary) and save for next dependency check
3. Save updated _package.json_
4. Show updated _package.json_ to user
5. 👩‍💻 Ask user for confirmation
   * Example dialog: "The package.json was changed. Please check and edit if necessary. If everything is alright please press Enter."


## 2. Check for new versions of dependencies from _requirements.txt_

**General information**

* This step is only necessary for python and hybrid plugins.
* Output of this step is that all develop dependencies are replaced with version numbers.

**Steps**

1. Gather github develop dependencies from _requirements.txt_ (e.g., `-e git+https://github.com/phovea/phovea_security_flask.git@develop#egg=phovea_security_flask`)
   * Check if that github link contains `phovea`, `caleydo`, `datavisyn`
   * Tip: Transform link to lower-case first to avoid different lower and upper case
2. For each dependency found:
   * Check on pypi.org if package available
      * Use HTTP request like https://pypi.org/pypi/phovea-server/json
      * See [example code](https://meet.google.com/linkredirect?authuser=0&dest=https%3A%2F%2Fgithub.com%2Fphovea%2Fgenerator-phovea%2Fpull%2F339%2Ffiles%23diff-6e5c8fe7c18c78c78c6f789263febd7dR260-R269)
   * If available: get last version number and replace github develop dependency with pypi version number (e.g., `>=4.0.0,<5.0.0`)
   * If not available (i.e., error 404 from HTTP request): Check github repository for last release and replace github develop dependency with github semver dependency (e.g., `-e git+https://github.com/phovea/phovea_security_flask.git@v4.0.0#egg=phovea_security_flask`)
       * 👩‍💻 Request bot token from user (if necessary) and save for next dependency check
3. Save updated _requirements.txt_
4. Show updated _requirements.txt_ to user
5. 👩‍💻 Ask user for confirmation
   * Example dialog: "The requirements.txt was changed. Please check and edit if necessary. If everything is alright please press Enter."


## 3. Check next version for current repo

**General information**

* This step is necessary for all plugin types.
* Output of this step is the next version number of the current plugin.
* Always log information and decision for next version number to console.
* If one major version has been found, we can skip the rest of the checks

**Steps**

1. Gather relevant PRs for this release 
   * Information about the PRs can be cached for release notes in a later step
2. Get attached release labels to these PRs
3. If a major label is available continue with step 8. Otherwise continue with dependency version check in the next step
4. Get package.json from master branch (or last github release)
5. Compare version of all `dependencies` compared to version from the master branch (or github last release)
   * If one dependency has changed in the major version the next version for the repo is major and we can skip the rest of the checks
6. Get requirements.txt from master branch (or last github release)
7. Compare version of all requirements compared to version from the master branch (or github last release)
   * If one requirement has changed in the major version the next version for the repo is major and we can skip the rest of the checks
8. Calculate next version number based on the gathered information
9. 👩‍💻 Prompt user to accept or define a different version number
   * The user might overwrite the calculated version number
   * Validate if entered version number is correct (has the correct format)
   * Should not be lower than the current version and been already used
10. Update _package.json_ with new version number

## 4. Create release branch

**Steps**

1. Create release branch with the name `release-x.x.x`
   *  Use git command

## 5. Prepare CHANGELOG.md

**Steps**

1. Gather release notes from merged PRs (since the last release)
   * Use cached information for the PRs, if available
2. Update CHANGELOG.md with a new section at the top of the file
3. 👩‍💻 Prompt user to confirm changelog and allow modification of the list (e.g., to fix typos
   * Example dialog: "The CHANGELOG.md was changed. Please check and edit if necessary. If everything is alright please press Enter."

## 6. Commit and push

**Steps**

1. Commit changed files (_package.json_, _requirements.txt_, and _CHANGELOG.md_)
2. Push release branch to GitHub

## 7. Create release pull request

**Steps**

1. 👩‍💻 Prompt user to enter/override the default assignee for the release PR
   * Use `git config user.name` as default
2. Create release PR that merges the `release-x.x.x` branch into the `master`
3. Show the latest changelog information in the body
4. Add release labels to PR (major, minor, patch)
   * Heads up: The release label is defined by the final version number (in case the user has modified it manually)
5. Assign reviewer and assignee for PR
   * The reviewer is empty and should be automatically assigned by Github from the CODEOWNERS file
   * Assignee: Use input from above
6. Print link to created Github PR

----

The user has to review the PR on GitHub and merge the release branch into the master branch → this triggers the following _finalize release_ step.

**Comment by oltionchampari** [comment]
When running the release generator in an already cloned repository,  the generator detects the 
 `.yo-rc.json` file and it saves all stored prompt values and configs in this file including the tokens.

Possible solution is not to store the tokens and enter them every time you run `yo phovea:prepare-release ` or to actually let the generator clone the repo.

**Comment by anita-steiner** [comment]
if you are not in a git directory, you get the following error:
events.js:288
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot destructure property 'name' of 'this.fs.readJSON(...)' as it is undefined.
    at Release._getRepositoryName (/workspaces/generator-phovea/generators/prepare-release/index.js:84:12)
    at Release.initializing (/workspaces/generator-phovea/generators/prepare-release/index.js:31:28)
    at Object.<anonymous> (/workspaces/generator-phovea/node_modules/yeoman-generator/lib/index.js:438:23)
    at /workspaces/generator-phovea/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /workspaces/generator-phovea/node_modules/run-async/index.js:24:19
    at /workspaces/generator-phovea/node_modules/yeoman-generator/lib/index.js:439:9
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15)
Emitted 'error' event on Release instance at:
    at Immediate.<anonymous> (/workspaces/generator-phovea/node_modules/yeoman-generator/lib/index.js:451:18)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15)

**Comment by oltionchampari** [comment]
It is meant to run on a cloned repo in develop branch.

**Comment by anita-steiner** [comment]
the process is different, as we described: "Press Enter to confirm changes. Type No and press Enter to open visual studio code and edit package.json." if the user says No, you change it nevertheless and open the editor

**Comment by anita-steiner** [comment]
if the user enters a wrong version (or a version that already exists), the generator should throw an exception

**Comment by anita-steiner** [comment]
the changelog files looks like this:
* Remove and ignore package-lock.json (datavisyn/tdp_core#280)
* Added no_cache option to DBViewBuilder (datavisyn/tdp_core#282)
* Migrate to Python 3.7 (datavisyn/tdp_core#270)
* # Conflicts: (datavisyn/tdp_core#undefined)
* #     tdp_core/db.py (datavisyn/tdp_core#undefined)
* # Conflicts: (datavisyn/tdp_core#undefined)
* #     .circleci/config.yml (datavisyn/tdp_core#undefined)
* #     .gitlab-ci.yml (datavisyn/tdp_core#undefined)
* #     requirements.txt (datavisyn/tdp_core#undefined)
* # Conflicts: (datavisyn/tdp_core#undefined)
* #     tdp_core/sql_filter.py (datavisyn/tdp_core#undefined)

**Comment by anita-steiner** [comment]
before you start: after you check, if you are in the develop branch - please pull

**Comment by anita-steiner** [comment]
assignee is not set in the pr

**Comment by anita-steiner** [comment]
don't add caleydo and datavisyn access key to the yo-rc file

**Comment by anita-steiner** [comment]
if there is nothing todo (no changes of the dependencies, no prs), why will the generator do a major release?

**Comment by anita-steiner** [comment]
changelog is wrong: after I make a release from 9.0.0 to 9.0.1, the change log looks like this:
* Release 9.0.0 (datavisyn/tdp_core#322)
* Remove `overflow: hidden` to fix download drop down (datavisyn/tdp_core#321)
* Change `buildId` to `JSON.stringify(buildId)` (datavisyn/tdp_core#317)
* Create extension point to connect the touring panel/Refactor LineupSidePanel (datavisyn/tdp_core#285)
* Refactor PanelTab extension point (datavisyn/tdp_core#319)
* Update dependencies and requirements (datavisyn/tdp_core#315)
* Update to Typescript 3.8 (datavisyn/tdp_core#308)
* Patch inconsistency of naming renderer getter and setter (datavisyn/tdp_core#305)
* Fixed disappearing of multiple push notifications (datavisyn/tdp_core#312)
* add CODEOWNERS file (datavisyn/tdp_core#296)
* Parse regular expression filter before storing to provenance graph (datavisyn/tdp_core#301)
* Fix date values in language strings (datavisyn/tdp_core#298)
* Configurable query delay for Select3 (datavisyn/tdp_core#295)
* Release 8.0.0 (datavisyn/tdp_core#289)
* Make DB timeout message more explicit (datavisyn/tdp_core#284)
* template changes (datavisyn/tdp_core#283)
* Remove and ignore package-lock.json (datavisyn/tdp_core#280)
* Added no_cache option to DBViewBuilder (datavisyn/tdp_core#282)
* Migrate to Python 3.7 (datavisyn/tdp_core#270)
* # Conflicts: (datavisyn/tdp_core#undefined)
* #     tdp_core/db.py (datavisyn/tdp_core#undefined)
* # Conflicts: (datavisyn/tdp_core#undefined)
* #     .circleci/config.yml (datavisyn/tdp_core#undefined)
* #     .gitlab-ci.yml (datavisyn/tdp_core#undefined)
* #     requirements.txt (datavisyn/tdp_core#undefined)
* # Conflicts: (datavisyn/tdp_core#undefined)
* #     tdp_core/sql_filter.py (datavisyn/tdp_core#undefined)

see also https://github.com/datavisyn/tdp_core/pull/324

**Comment by oltionchampari** [comment]
> the changelog files looks like this:
> 
> * Remove and ignore package-lock.json ([datavisyn/tdp_core#280](https://github.com/datavisyn/tdp_core/pull/280))
> * Added no_cache option to DBViewBuilder ([datavisyn/tdp_core#282](https://github.com/datavisyn/tdp_core/pull/282))
> * Migrate to Python 3.7 ([datavisyn/tdp_core#270](https://github.com/datavisyn/tdp_core/pull/270))
> * # Conflicts: (datavisyn/tdp_core#undefined)
> * # tdp_core/db.py (datavisyn/tdp_core#undefined)
> * # Conflicts: (datavisyn/tdp_core#undefined)
> * # .circleci/config.yml (datavisyn/tdp_core#undefined)
> * # .gitlab-ci.yml (datavisyn/tdp_core#undefined)
> * # requirements.txt (datavisyn/tdp_core#undefined)
> * # Conflicts: (datavisyn/tdp_core#undefined)
> * # tdp_core/sql_filter.py (datavisyn/tdp_core#undefined)

Merge conflicts don't belong in the release notes right?

**Comment by thinkh** [comment]
I tested this with phovea_ui. The develop branch has the version `4.0.1-SNAPSHOT` and phovea_core as dependency. Both have no merged PRs, but I get:

>  Next version: 5.0.0

Why do I get a major version here? In best case the command should notice that no PR has been merged since the last release and suggest to cancel the release. If this is not implemented, I would expect that the next version is a patch release.

**Comment by anita-steiner** [comment]
I tested it with patentbay: tried to make version 3.0.1 and the label of the pr is: release: null; see https://github.com/datavisyn/patentbay/pull/880

**Comment by thinkh** [comment]
> Checkout new branch:  git checkout -brelease-4.0.1

There is a space after `-b` missing. I do not know if it is just the log or the executed command.

**Comment by oltionchampari** [comment]
> I tested this with phovea_ui. The develop branch has the version `4.0.1-SNAPSHOT` and phovea_core as dependency. Both have no merged PRs, but I get:
> 
> > Next version: 5.0.0
> 
> Why do I get a major version here? In best case the command should notice that no PR has been merged since the last release and suggest to cancel the release. If this is not implemented, I would expect that the next version is a patch release.

It checks if there is any remote major dependency with a a major version.

**Comment by anita-steiner** [comment]
it would be good to have a summarize of the pr before pushing it to github

**Comment by thinkh** [comment]
The last phovea_ui release has already [phovea_core v4.0.0 as dependency](https://github.com/phovea/phovea_ui/blob/v4.0.0/package.json#L58). Hence, there is no change at all.

**Comment by thinkh** [comment]
Why do I get a JSON output for the PR? Everything else looks so well integrated in the command line.

```json
{
  method: 'POST',
  uri: 'https://caleydo-bot:6d259a8618ec01adeab56920369379a194e99001@api.github.com/repos/phovea/phovea_ui/pulls',
  body: {
    title: 'Release test 4.0.1',
    head: 'release-4.0.1',
    body: '## Release notes\n' +
      '\n' +
      '\n' +
      '\n' +
      '\n' +
      '### Release dependencies first\n' +
      '\n' +
      'In case of dependent Phovea/TDP repositories follow [dependency tree](https://wiki.datavisyn.io/phovea/fundamentals/development-process#dependency-hierarchy) from the top:\n' +
      '\n' +
      ' \n' +
      '### �🏁 Finish line\n' +
      '\n' +
      '* [ ] Inform colleagues and customers about the release\n' +
      '* [ ] Celebrate the new release 🥳\n' ,
    base: 'master'
  },
  headers: { 'User-Agent': 'request' },
  json: true
}
```

**Comment by oltionchampari** [comment]
> The last phovea_ui release has already [phovea_core v4.0.0 as dependency](https://github.com/phovea/phovea_ui/blob/v4.0.0/package.json#L58). Hence, there is no change at all.

At the moment it doesn't check if those versions are already in master, but it can be done.

**Comment by oltionchampari** [comment]
> Why do I get a JSON output for the PR? Everything else looks so well integrated in the command line.
> 
> ```
> {
>   method: 'POST',
>   uri: 'https://caleydo-bot:6d259a8618ec01adeab56920369379a194e99001@api.github.com/repos/phovea/phovea_ui/pulls',
>   body: {
>     title: 'Release test 4.0.1',
>     head: 'release-4.0.1',
>     body: '## Release notes\n' +
>       '\n' +
>       '\n' +
>       '\n' +
>       '\n' +
>       '### Release dependencies first\n' +
>       '\n' +
>       'In case of dependent Phovea/TDP repositories follow [dependency tree](https://wiki.datavisyn.io/phovea/fundamentals/development-process#dependency-hierarchy) from the top:\n' +
>       '\n' +
>       ' \n' +
>       '### �🏁 Finish line\n' +
>       '\n' +
>       '* [ ] Inform colleagues and customers about the release\n' +
>       '* [ ] Celebrate the new release 🥳\n' ,
>     base: 'master'
>   },
>   headers: { 'User-Agent': 'request' },
>   json: true
> }
> ```
A console log wandering about...

**Comment by oltionchampari** [comment]
> it would be good to have a summarize of the pr before pushing it to github

You mean show the user the composed pr before pushing? Allow editing ?

**Comment by thinkh** [comment]
My PR https://github.com/phovea/phovea_ui/pull/105/files has:

* a `release: null` label
* a lot of chmod changes and I still have lots of chmod changes that are waiting to commit... 

![grafik](https://user-images.githubusercontent.com/5851088/77082213-0aace700-69fc-11ea-94ec-2b04f1f03da2.png)

**Comment by anita-steiner** [comment]
you have to check also devDependencies AND optionalDependencies as https://github.com/datavisyn/tdp_comments/pull/89

**Comment by oltionchampari** [comment]
> if there is nothing todo (no changes of the dependencies, no prs), why will the generator do a major release?

In this case throw an error?

**Comment by oltionchampari** [comment]
> you have to check also devDependencies AND optionalDependencies as [datavisyn/tdp_comments#89](https://github.com/datavisyn/tdp_comments/pull/89)

devdependencies why ?

**Comment by anita-steiner** [comment]
> > if there is nothing todo (no changes of the dependencies, no prs), why will the generator do a major release?
> 
> In this case throw an error?

no but a hin 'There is nothing todo. Do you really want to release'. But don't make a major release as default if there is nothing todo

**Comment by thinkh** [comment]
I gave the phovea_ui another try and this time I had no chmod problems. So it might be really released to my WSL setup.

**Comment by anita-steiner** [comment]
see also https://github.com/phovea/generator-phovea/issues/424
