### ISSUE TITLE
Run phovea:update in ueber context

### ISSUE THREAD

**Issue by thinkh** [phovea/generator-phovea#34]
To create build information for web plugins (#33) I have to go through all cloned repos and manually run `yo phovea:update` within each directory.

**Expected**
It would be really hand if I can run `yo phovea:update` from the ueber context directory and it will go through all web plugins automatically. 

**Current status**
Running `yo phovea:update` in the ueber context results in the following error message:

```
D:\dev\repos\phovea\ueber_context>yo phovea:update

events.js:160
      throw er; // Unhandled 'error' event
      ^
AssertionError: D:\dev\repos\phovea\provenance_steering\README.md doesn't exist
    at EditionInterface.module.exports [as read] (D:\dev\repos\phovea\generator-phovea\node_modules\mem-fs-editor\lib\actions\read.js:18:3)
    at Generator.initializing (D:\dev\repos\phovea\generator-phovea\generators\update\index.js:10:65)
    at Object.<anonymous> (D:\dev\repos\phovea\generator-phovea\node_modules\yeoman-generator\lib\base.js:439:23)
    at D:\dev\repos\phovea\generator-phovea\node_modules\run-async\index.js:26:25
    at D:\dev\repos\phovea\generator-phovea\node_modules\run-async\index.js:25:19
    at D:\dev\repos\phovea\generator-phovea\node_modules\yeoman-generator\lib\base.js:440:9
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by sgratzl** [comment]
why does: `./forEach yo phovea:update` not work?

**Comment by thinkh** [comment]
Because I didn't know that this exists.

**Comment by sgratzl** [comment]
see also http://phovea.caleydo.org/contributors/cheatsheet/ -> For Each

**Comment by thinkh** [comment]
Thanks. Then I close this issue.
